
import turtle

turtle.speed(7)

turtle.bgcolor("#8DACFF")

turtle.forward(300)
turtle.left(90)

turtle.fillcolor("#B36C0F")
turtle.begin_fill()
turtle.forward(200)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(140)
turtle.end_fill()

turtle.left(180)
turtle.forward(110)

turtle.fillcolor("#2638AC")
turtle.begin_fill()
turtle.left(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(135)
turtle.left(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(215)
turtle.left(90)
turtle.end_fill()

turtle.penup()
turtle.forward(110)
turtle.left(90)
turtle.forward(80)

turtle.fillcolor("#F2F20F")
turtle.begin_fill()
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.pendown()
turtle.right(90)
turtle.forward(30)
turtle.end_fill()


turtle.fillcolor("#2638AC")
turtle.begin_fill()

size = 30
for _ in range(4):
    turtle.left(90) 
    turtle.forward(size)
turtle.end_fill()

turtle.penup()
turtle.left(90)
turtle.forward(size)
turtle.pendown()

turtle.fillcolor("#F01C1C")
turtle.begin_fill()
turtle.right(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(size)
turtle.right(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(size)
turtle.right(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(30)
turtle.end_fill()

turtle.penup()
turtle.left(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(30)
turtle.pendown()

turtle.fillcolor("#F01C1C")
turtle.begin_fill()
turtle.forward(size)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(size)
turtle.right(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(230)

turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

turtle.penup()
turtle.left(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(100)
turtle.pendown()

turtle.fillcolor("#F5F1C1")
turtle.begin_fill()
turtle.forward(60)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(size)

turtle.penup()
turtle.left(90)
turtle.forward(size)
turtle.right(90)
turtle.forward(size)
turtle.left(90)
turtle.forward(60)
turtle.end_fill()

turtle.fillcolor("#F5F1C1")
turtle.begin_fill()
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(30)
turtle.pendown()

turtle.fillcolor("#F5F1C1")
turtle.begin_fill()
turtle.forward(90)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

turtle.fillcolor("#000000")
turtle.begin_fill()
turtle.penup()
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(70)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(70)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(30)
turtle.end_fill()

turtle.fillcolor("#F5F1C1") # egg colur
turtle.begin_fill()
turtle.penup()
turtle.forward(-30)
turtle.left(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(70)
turtle.left(90)
turtle.forward(60)
turtle.pendown()

turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(240)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.end_fill()

turtle.penup()
turtle.forward(-60)
turtle.left(90)
turtle.forward(90)
turtle.pendown()

turtle.fillcolor("#2638AC") #ฺblue
turtle.begin_fill()

size = 30
for _ in range(4):
    turtle.left(90) 
    turtle.forward(size)
turtle.end_fill()


turtle.fillcolor("#F01C1C") #red
turtle.begin_fill()
turtle.penup()
turtle.forward(150)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.end_fill()

turtle.fillcolor("#F01C1C") 

turtle.penup()
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(60)
turtle.pendown()

turtle.fillcolor("#2638AC")
turtle.begin_fill()
for _ in range(4):
    turtle.left(90) 
    turtle.forward(size)
turtle.end_fill()

turtle.fillcolor("#F01C1C")
turtle.begin_fill()

turtle.left(90)
turtle.forward(180)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(60)

turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)

turtle.end_fill()

turtle.fillcolor("#B36C0F") 
turtle.begin_fill()
turtle.forward(160)
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(60)

turtle.end_fill()

turtle.right(90)
turtle.forward(90)

turtle.fillcolor("#B36C0F")
turtle.begin_fill()
for _ in range(2):
    turtle.left(90) 
    turtle.forward(80)
    turtle.left(90) 
    turtle.forward(100)
turtle.end_fill()

turtle.fillcolor("#F5F1C1")
turtle.begin_fill()
for _ in range(2) :
    turtle.left(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(60)
turtle.end_fill()

turtle.penup()
turtle.forward(-160)
turtle.left(90)
turtle.forward(150)
turtle.pendown()

turtle.fillcolor("#F5F1C1")
turtle.begin_fill()
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)

for _ in range(2):
    turtle.left(90)
    turtle.forward(30)

turtle.right(90)
turtle.forward(30)

for _ in range(2):
    turtle.left(90)
    turtle.forward(30)

turtle.right(90)
turtle.forward(30)
turtle.end_fill()

turtle.penup()
for _ in range(2):
    turtle.right(90)
    turtle.forward(120)
turtle.forward(45)
turtle.pendown()

turtle.fillcolor("#2638AC")
turtle.begin_fill()
for _ in range(4):
    turtle.right(90)
    turtle.forward(30)
turtle.end_fill()

turtle.penup()
turtle.forward(-30)
turtle.pendown()

turtle.forward(-45)
for _ in range(2):
    turtle.right(90)
    turtle.forward(90)
    turtle.left(90)
    turtle.forward(30)

turtle.fillcolor("#B36C0F")
turtle.begin_fill()
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(35)
turtle.right(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(45)

turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(90)
turtle.end_fill()

turtle.penup()
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(270)
turtle.pendown()

turtle.fillcolor("#F2F20F")
turtle.begin_fill()
for _ in range(5):
    turtle.left(90)
    turtle.forward(30)

turtle.end_fill()
turtle.done()